### PR TITLE
Update .editorconfig to display errors when using the 'var' keyword instead of explicit types

### PR DESCRIPTION
**Pull request by StevenRasmussen**
All current uses of `var` were updated to use explicit types.

### CODE REVIEW

**Comment by madskristensen** [comment]
Thanks

**Comment by yannduran** [comment]
Why? And why was there no discussion?

**Comment by reduckted** [comment]
To enforce consistency. It was already a suggestion. This just enforces that code style. Given that there were only six code changes, most places were already following the convention.

**Comment by mrlacey** [comment]
> Why? And why was there no discussion?

The discussion was had as part of https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/pull/125

**Comment by yannduran** [comment]
Thanks, I didn't see #125 until after I saw this.

**Pull request merged**
