### PR TITLE
Rename infobar

### LINKED ISSUE #48: Infobar.cs file should be renamed to InfoBar.cs
[Infobar.cs](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/master/src/Community.VisualStudio.Toolkit.Shared/Notifications/Infobar.cs) doesn't match the format used in related methods.  For instance, [CreateInfoBar](https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/blob/43235dd7606655844ba5cf881469b1f427877cf7/src/Community.VisualStudio.Toolkit.Shared/Notifications/Infobar.cs#L16).

### PR DESCRIPTION
**Pull request by shaggygi**
Fixes #48.

Updated file name and summaries.

### CODE REVIEW

**Review by yannduran — COMMENTED** [review]
Why would you want to add a "_" to InfoBar?

**Review by yannduran — COMMENTED** [review]
OK, ignore my previous comment.

**Comment by shaggygi** [comment]
> Why would you want to add a "_" to InfoBar?

Was having brain toot on how to force the casing 😄

**Comment by madskristensen** [comment]
Thanks

**Pull request merged**
